/** @layer game/character */
import { SYSTEM_ID } from '../../contracts/protocol.mjs';
import { RESULT_CODES } from '../../contracts/results.mjs';
import { EQUIPMENT_REFUSALS, PROFICIENCY_RANK_LETTERS } from '../../contracts/domains/items.mjs';
import { checkCaster } from '../effects/requirements.mjs';
import { unitTurnComplete } from '../combat/phases.mjs';
import { holdsProficiencyRank } from '../progression/rules.mjs';

/* -------------------------------------------- */
/*  Character inventory vocabulary              */
/* -------------------------------------------- */
export const CHARACTER_INVENTORY_LIMITS = Object.freeze({
  equipment: 5,
  pockets: 5,
  spells: 15,
  abilities: 15
});

const ABILITY_TABLE_SUBTYPES = new Set(['Active', 'Weapon Art', 'Mount']);
const POCKET_TYPES = new Set(['Consumable', 'Miscellaneous', 'Resource']);
const TRANSFERABLE_TYPES = new Set(['Equipment', 'Consumable', 'Miscellaneous', 'Resource']);
const WIELDABLE = new Set(['Weapon', 'Staff', 'Attack']);
const EQUIPPABLE = new Set(['Shield', 'Accessory']);

/* -------------------------------------------- */
/*  Classification and capacity                 */
/* -------------------------------------------- */
/** Which Character table owns an Item, or null for Classes and passive features. */
function characterItemSection(item) {
  if (item?.type === 'Equipment') return 'equipment';
  if (item?.type === 'Spell') return 'spells';
  if (item?.type === 'Ability' && ABILITY_TABLE_SUBTYPES.has(itemSystem(item).itemType)) return 'abilities';
  if (POCKET_TYPES.has(item?.type)) return 'pockets';
  return null;
}

/** Whether an item was generated by an innate grant rather than carried normally. */
export function isInnateCharacterItem(item) {
  return item?.innateGrant === true;
}

/** The Character sheet table an item is listed in. Innate Equipment fills no slot, so it's listed in none. */
export function characterItemListing(item) {
  const section = characterItemSection(item);
  if (section === 'equipment' && isInnateCharacterItem(item)) return null;
  return section;
}

/**
 * A Character's equipment capacity: its derived `system.equipment.slots`, which compileCharacterData seeds from the
 * base below and item modifiers such as Armed to the Teeth add to. A unit whose data hasn't been prepared yet gets
 * the base.
 * @param {number|undefined} equipmentSlots The unit's compiled slot count.
 * @returns {number}
 */
export function characterEquipmentCapacity(equipmentSlots) {
  const slots = Number(equipmentSlots);
  return Number.isFinite(slots) && slots >= 0 ? slots : CHARACTER_INVENTORY_LIMITS.equipment;
}

/** Count only equipment which consumes a carrying slot. */
export function characterEquipmentCount(items) {
  return iterable(items).filter(item => item?.type === 'Equipment' && !isInnateCharacterItem(item)).length;
}

/** Count pocket entries. A Resource's quantity stacks within one entry. */
export function characterPocketCount(items) {
  return iterable(items).filter(item => POCKET_TYPES.has(item?.type)).length;
}

/**
 * Find the Resource stack compatible with an incoming Resource: same name, same unit price and the same vendor tags
 * (vendorTags), so a tagged unit never loses its tag to a merge and an untagged one never gains one.
 * @param {Iterable<object>} items The candidate stacks, as Items or item data carrying their flags.
 * @param {object} incoming The arriving Resource.
 * @param {{sold: string[], buyback: ?object}} [tags] The tags the arriving copy will carry, when a vendor purchase
 *   or sale changes them on the way; the incoming Item's own tags otherwise.
 * @returns {?object}
 */
export function matchingResourceStack(items, incoming, tags = vendorTags(incoming)) {
  if (incoming?.type !== 'Resource') return null;
  const price = Number(itemSystem(incoming).cost?.perUnit) || 0;
  return iterable(items).find(item => item?.type === 'Resource'
    && item.name === incoming.name
    && (Number(itemSystem(item).cost?.perUnit) || 0) === price
    && sameVendorTags(vendorTags(item), tags)) ?? null;
}

/* -------------------------------------------- */
/*  Vendor tags                                 */
/* -------------------------------------------- */
/**
 * The hidden system flags a vendor sale or purchase leaves on an Item until the table's Reset Downtime strips them
 * (document-writes/economy.mjs). `vendorSold` lists the Vendor Actor uuids that sold the Item, and each of them
 * refuses to buy it back. `vendorBuyback` sits on a Vendor's stock copy of something a party sold it: the seller's
 * haggle key and the per-unit gold paid, which that party buys it back at.
 */
export const VENDOR_SOLD_FLAG = 'vendorSold';
export const VENDOR_BUYBACK_FLAG = 'vendorBuyback';

/**
 * An Item's vendor tags read from its system flags, normalized so two copies compare equal exactly when they carry
 * the same tags: the selling Vendors sorted without repeats, and the buyback or null.
 * @param {{flags?: object}} item An Item or item data carrying its flags.
 * @returns {Readonly<{sold: readonly string[], buyback: ?Readonly<{vendorUuid: string, key: string,
 *   unitPrice: number}>}>}
 */
export function vendorTags(item) {
  const flags = item?.flags?.[SYSTEM_ID] ?? {};
  const listed = Array.isArray(flags[VENDOR_SOLD_FLAG]) ? flags[VENDOR_SOLD_FLAG] : [];
  const sold = [...new Set(listed.map(uuid => String(uuid ?? '')).filter(Boolean))].sort();
  const raw = flags[VENDOR_BUYBACK_FLAG];
  const buyback = raw && typeof raw === 'object' && typeof raw.key === 'string' && raw.key
    && Number.isFinite(Number(raw.unitPrice))
    ? Object.freeze({
      vendorUuid: String(raw.vendorUuid ?? ''), key: raw.key, unitPrice: Math.max(0, Math.floor(Number(raw.unitPrice)))
    })
    : null;
  return Object.freeze({ sold: Object.freeze(sold), buyback });
}

/** Whether an Item carries either vendor tag, which the Reset Downtime sweep strips. */
export function hasVendorTags(item) {
  const tags = vendorTags(item);
  return tags.sold.length > 0 || tags.buyback !== null;
}

function sameVendorTags(left, right) {
  const leftSold = left?.sold ?? [];
  const rightSold = right?.sold ?? [];
  if (leftSold.length !== rightSold.length || leftSold.some((uuid, index) => uuid !== rightSold[index])) return false;
  const [one, other] = [left?.buyback ?? null, right?.buyback ?? null];
  if (!one || !other) return one === other;
  return one.vendorUuid === other.vendorUuid && one.key === other.key && one.unitPrice === other.unitPrice;
}

/**
 * Decide what leaves a unit whose equipment no longer fits its slots, as when a passive granting slots is lost.
 * Unequipped pieces go first, newest of them first, and only then the ones the unit is using.
 * engine/character/commands.mjs moves exactly these to the party Convoy.
 * @param {{items: object[], equipmentSlots?: number}} carrier The unit, with its prepared slot count.
 * @returns {{overflowing: boolean, capacity: number, carried: number, itemIds: string[]}}
 */
export function planEquipmentOverflow(carrier) {
  const capacity = characterEquipmentCapacity(carrier.equipmentSlots);
  const listed = iterable(carrier.items)
    .filter(item => item?.type === 'Equipment' && !isInnateCharacterItem(item));
  const surplus = listed.length - capacity;
  if (surplus <= 0) {
    return { overflowing: false, capacity, carried: listed.length, itemIds: [] };
  }
  const itemIds = listed
    .map((item, index) => ({ item, index, equipped: isEquippedItem(item) }))
    .sort((left, right) => (left.equipped === right.equipped
      ? right.index - left.index
      : Number(left.equipped) - Number(right.equipped)))
    .slice(0, surplus)
    .map(entry => itemId(entry.item));
  return { overflowing: true, capacity, carried: listed.length, itemIds };
}

/** Whether a carried piece of equipment is currently in use, and so kept back until nothing idle is left. */
function isEquippedItem(item) {
  const field = equipmentStateField(item);
  return field ? itemSystem(item)[field] === true : false;
}

/**
 * Whether a unit has room for an incoming item. engine/character/commands.mjs checks it before a transfer, and the
 * Character sheet before a drop, so both follow the same rules. A Resource that stacks onto one the unit already
 * carries comes back with that stack's `stackId`.
 * @param {{items: object[], equipmentSlots?: number}} carrier The receiving unit, with its prepared slot count.
 * @param {object} incoming The Item arriving.
 */
export function characterItemAdmission(carrier, incoming) {
  const carried = iterable(carrier.items);
  const section = characterItemSection(incoming);
  const system = itemSystem(incoming);

  if (incoming?.type === 'Ability' && system.itemType === 'Passive') {
    return acceptAdmission('features');
  }
  if (!section) return refuseAdmission('inventory.item-type', { itemType: incoming?.type ?? '' });

  if (section === 'equipment') {
    // A unit may carry only one Armor, worn or not.
    if (system.itemType === 'Armor'
      && carried.some(item => item.type === 'Equipment' && itemSystem(item).itemType === 'Armor')) {
      return refuseAdmission('inventory.armor-full');
    }
    const limit = characterEquipmentCapacity(carrier.equipmentSlots);
    if (!isInnateCharacterItem(incoming) && characterEquipmentCount(carried) >= limit) {
      return refuseAdmission('inventory.equipment-full', { limit });
    }
  }

  if (section === 'spells') {
    const count = carried.filter(item => item.type === 'Spell').length;
    if (count >= CHARACTER_INVENTORY_LIMITS.spells) {
      return refuseAdmission('inventory.spells-full', {
        limit: CHARACTER_INVENTORY_LIMITS.spells
      });
    }
  }

  if (section === 'abilities') {
    const count = carried.filter(item => item.type === 'Ability'
      && ABILITY_TABLE_SUBTYPES.has(itemSystem(item).itemType)).length;
    if (count >= CHARACTER_INVENTORY_LIMITS.abilities) {
      return refuseAdmission('inventory.abilities-full', {
        limit: CHARACTER_INVENTORY_LIMITS.abilities
      });
    }
  }

  if (section === 'pockets') {
    const stack = matchingResourceStack(carried, incoming);
    if (!stack && characterPocketCount(carried) >= CHARACTER_INVENTORY_LIMITS.pockets) {
      return refuseAdmission('inventory.pockets-full', {
        limit: CHARACTER_INVENTORY_LIMITS.pockets
      });
    }
    return acceptAdmission(section, { stackId: stack?.id ?? stack?._id ?? null });
  }

  return acceptAdmission(section);
}

/** Items which move between Actors rather than being learned as a copy. */
export function characterItemTransfers(item) {
  return TRANSFERABLE_TYPES.has(item?.type) && !isInnateCharacterItem(item);
}

/**
 * Whether a running encounter locks a player out of a handover: sheet transfers between units, and taking Items or
 * gold out of a Convoy. Deposits into a Convoy stay open while the unit has turn left (planConvoyDeposit in
 * game/economy/trade.mjs), and a GM is never locked out. During an encounter, players hand items over with the trade
 * command in engine/economy/trade.mjs, which checks range and action costs.
 * @param {object} facts `inCombat` and `isGM`.
 * @returns {boolean} Whether the handover is locked.
 */
export function handoverLockedByEncounter({ inCombat = false, isGM = false } = {}) {
  return inCombat === true && isGM !== true;
}

/** Whether an item dragged from another actor may be received. Abilities and Spells copy, and innate items can't. */
export function characterActorItemDropAllowed(item) {
  if (isInnateCharacterItem(item)) return false;
  if (item?.type === 'Ability' || item?.type === 'Spell') return true;
  return characterItemTransfers(item);
}

/* -------------------------------------------- */
/*  Equipment rules                             */
/* -------------------------------------------- */
/**
 * Whether wearing an Item is the whole of its use. A shield or accessory activates nothing, so a click on one in
 * ui/controls/targeting.mjs is its equip toggle, and equipmentChangeRefusal below asks no Action for it.
 */
export function isEquipOnlyItem(item) {
  return item?.type === 'Equipment' && EQUIPPABLE.has(itemSystem(item).itemType);
}

/** The persisted state field controlled by an inventory-row toggle. */
export function equipmentStateField(item) {
  const system = itemSystem(item);
  if ((item?.type === 'Equipment' && ['Weapon', 'Staff'].includes(system.itemType))
    || (item?.type === 'Spell' && system.itemType === 'Attack')) return 'isWielded';
  if (item?.type === 'Equipment' && system.itemType === 'Armor') return 'isWorn';
  if (item?.type === 'Equipment' && EQUIPPABLE.has(system.itemType)) return 'isEquipped';
  if (item?.type === 'Ability' && system.itemType === 'Mount') return 'isEquipped';
  return null;
}

/**
 * The item updates that toggle one piece of equipment on or off, including unequipping whatever it replaces, or a
 * refusal code when the unit can't. Called by engine/character/commands.mjs, which passes the updates to
 * planEquipmentToggleConsequences and the actor writer. `notices` lists what the UI tells the player afterwards.
 */
export function buildEquipmentToggle(actor, selected, { isGM = false, inCombat = false } = {}) {
  const items = iterable(actor.items);
  const field = equipmentStateField(selected);
  if (!field) return refuseToggle(EQUIPMENT_REFUSALS.NOT_EQUIPPABLE);

  const actorSystem = actor.system ?? {};
  const gate = equipmentChangeRefusal(actorSystem, selected, { isGM, inCombat });
  if (gate) return refuseToggle(gate);

  const system = itemSystem(selected);
  const enabled = system[field] !== true;
  if (!enabled) return acceptToggle([{ _id: itemId(selected), [`system.${field}`]: false }], field, false);

  if (field === 'isWielded') {
    const check = weaponProficiency(actorSystem, selected);
    if (!check.ok) return refuseToggle(check.code, check);
    if (Number(system.uses?.current) < 1) {
      return refuseToggle(EQUIPMENT_REFUSALS.ITEM_DEPLETED, { itemName: selected.name });
    }
  }

  if (field === 'isWorn') {
    if (inCombat && !isGM) return refuseToggle(EQUIPMENT_REFUSALS.ARMOR_IN_COMBAT);
    const check = armorProficiency(actorSystem, selected);
    if (!check.ok) return refuseToggle(check.code, check);
  }

  const authored = equipmentRequirements(actor, selected);
  if (!authored.ok) {
    return refuseToggle(EQUIPMENT_REFUSALS.REQUIREMENTS_UNMET, {
      itemName: selected.name, requirementNames: authored.failedNames
    });
  }

  const updates = [];
  const notices = [];
  if (field === 'isWielded') {
    for (const item of items) {
      if (itemId(item) !== itemId(selected) && itemSystem(item).isWielded === true) {
        updates.push({ _id: itemId(item), 'system.isWielded': false });
      }
    }
    if (system.weapon?.twoHanded) {
      for (const item of items) {
        if (itemSystem(item).itemType === 'Shield' && itemSystem(item).isEquipped === true) {
          updates.push({ _id: itemId(item), 'system.isEquipped': false });
        }
      }
    }
  } else if (field === 'isWorn') {
    for (const item of items) {
      if (itemId(item) !== itemId(selected) && itemSystem(item).itemType === 'Armor' && itemSystem(item).isWorn === true) {
        updates.push({ _id: itemId(item), 'system.isWorn': false });
      }
    }
  } else if (system.itemType === 'Shield') {
    for (const item of items) {
      const other = itemSystem(item);
      if (itemId(item) !== itemId(selected) && other.itemType === 'Shield' && other.isEquipped === true) {
        updates.push({ _id: itemId(item), 'system.isEquipped': false });
      }
      if (other.isWielded === true && WIELDABLE.has(other.itemType) && other.weapon?.twoHanded) {
        updates.push({ _id: itemId(item), 'system.isWielded': false });
        notices.push(EQUIPMENT_NOTICES.TWO_HANDED_UNWIELDED);
      }
    }
  } else if (selected.type === 'Ability' && system.itemType === 'Mount') {
    const otherMount = items.find(item => itemId(item) !== itemId(selected) && item?.type === 'Ability'
      && itemSystem(item).itemType === 'Mount' && itemSystem(item).isEquipped === true);
    if (otherMount) {
      return refuseToggle(EQUIPMENT_REFUSALS.MOUNT_ALREADY_ACTIVE, {
        actorName: String(actor.name ?? ''), itemName: otherMount.name
      });
    }
  }
  updates.push({ _id: itemId(selected), [`system.${field}`]: true });
  return acceptToggle(dedupeUpdates(updates), field, true, notices);
}

/**
 * Whether wielding a weapon would take off the unit's equipped shield, as buildEquipmentToggle does for a two-handed
 * one. The Combat Preview leaves such a weapon out of its switcher (projectWeaponChoicesAs in
 * foundry/adapters/projections/characters.mjs).
 * @param {Iterable<object>} items The unit's items.
 * @param {object} weapon The weapon it would wield.
 * @returns {boolean}
 */
export function wieldTakesOffShield(items, weapon) {
  return Boolean(itemSystem(weapon).weapon?.twoHanded) && iterable(items)
    .some(item => itemSystem(item).itemType === 'Shield' && itemSystem(item).isEquipped === true);
}

/**
 * The items to unequip because their caster requirements no longer hold, for reconcileCharacterEquipmentEffects in
 * engine/character/commands.mjs. foundry/hooks/actors.mjs asks for that check after an actor, effect or item
 * change, not only after a toggle.
 * @param {object} actor The unit, with the values its conditions read as `conditionSelf`.
 * @returns {{updates: object[], unequipped: readonly {itemId: string, itemName: string,
 *   requirementNames: readonly string[]}[]}}
 */
export function planRequirementUnequips(actor) {
  const updates = [];
  const unequipped = [];
  for (const item of iterable(actor.items)) {
    const field = equipmentStateField(item);
    if (!field || itemSystem(item)[field] !== true) continue;
    const authored = equipmentRequirements(actor, item);
    if (authored.ok) continue;
    updates.push({ _id: itemId(item), [`system.${field}`]: false });
    unequipped.push(Object.freeze({
      itemId: itemId(item), itemName: String(item?.name ?? ''), requirementNames: authored.failedNames
    }));
  }
  return { updates, unequipped: Object.freeze(unequipped) };
}

/** Notice ids returned by buildEquipmentToggle for the UI to display after persistence. */
export const EQUIPMENT_NOTICES = Object.freeze({
  TWO_HANDED_UNWIELDED: 'two-handed-unwielded'
});

/**
 * Whether a unit may change this piece of equipment now. This only checks; nothing is spent here. Players are held
 * to the turn economy, a GM is not. Putting on or taking off a weapon or armor needs the unit's Action, in or out
 * of an encounter. A shield or accessory only needs the unit to have some turn left during an encounter
 * (unitTurnComplete in game/combat/phases.mjs), and nothing outside one.
 * @param {object} actorSystem The unit's system data.
 * @param {object} selected The Item being toggled.
 * @param {{isGM: boolean, inCombat: boolean}} context Caller permission and whether an encounter is underway.
 * @returns {string|null} The refusal code, or null to allow.
 */
function equipmentChangeRefusal(actorSystem, selected, { isGM, inCombat }) {
  if (isGM) return null;
  const turn = actorSystem.turn ?? {};
  if (isEquipOnlyItem(selected)) {
    return inCombat && unitTurnComplete(turn) ? EQUIPMENT_REFUSALS.TURN_OVER : null;
  }
  if (unitTurnComplete(turn)) return EQUIPMENT_REFUSALS.TURN_OVER;
  if (turn.actionAvailable !== true) return EQUIPMENT_REFUSALS.ACTION_REQUIRED;
  return null;
}

/* -------------------------------------------- */
/*  Internal helpers                            */
/* -------------------------------------------- */
function itemSystem(item) {
  return item?.system ?? {};
}

function itemId(item) {
  return item?.id ?? item?._id ?? '';
}

function iterable(items) {
  return Array.isArray(items) ? [...items] : items ? Array.from(items) : [];
}

function acceptAdmission(section, data = {}) {
  return { ok: true, code: 'inventory.accepted', section, ...data };
}

function refuseAdmission(code, data = {}) {
  return { ok: false, code, ...data };
}

/**
 * Whether the unit has the rank to wield a weapon (holdsProficiencyRank in game/progression/rules.mjs). A proficiency
 * the unit has no entry for is refused as unknown rather than unmet.
 */
function weaponProficiency(actorSystem, item) {
  const system = itemSystem(item);
  const required = String(system.weapon?.req ?? '').trim().toLowerCase();
  const rank = Math.max(0, Number(system.weapon?.rank) || 0);
  const totals = Object.fromEntries(Object.entries(actorSystem.prof ?? {})
    .filter(([, node]) => node).map(([key, node]) => [key, node.total]));
  const held = holdsProficiencyRank(totals, required, rank, null);
  if (held === null) return { ok: false, code: EQUIPMENT_REFUSALS.PROFICIENCY_UNKNOWN, required };
  if (!held) return {
    ok: false,
    code: EQUIPMENT_REFUSALS.PROFICIENCY_REQUIRED,
    required,
    rank,
    rankLabel: PROFICIENCY_RANK_LETTERS[Math.min(PROFICIENCY_RANK_LETTERS.length, Math.max(1, rank)) - 1],
    itemName: item.name
  };
  return { ok: true };
}

function armorProficiency(actorSystem, item) {
  const requiredName = String(itemSystem(item).armor?.req ?? '').trim().toLowerCase();
  if (!requiredName || requiredName === 'none') return { ok: true };
  const required = { light: 1, medium: 2, heavy: 3 }[requiredName];
  if (!required) return { ok: false, code: EQUIPMENT_REFUSALS.ARMOR_PROFICIENCY_UNKNOWN, required: requiredName };
  const rank = Number(actorSystem.prof?.armor?.total ?? actorSystem.prof?.armor) || 0;
  if (rank < required) return {
    ok: false,
    code: EQUIPMENT_REFUSALS.ARMOR_PROFICIENCY_REQUIRED,
    required: requiredName,
    rank: required,
    itemName: item.name
  };
  return { ok: true };
}

/**
 * Check an item's caster requirements for equipment toggles and planRequirementUnequips. Target requirements are
 * skipped, and so is every check when the actor has no `conditionSelf`. Silence isn't checked, because it blocks
 * using an item, not carrying it.
 */
function equipmentRequirements(actor, item) {
  const requirements = itemSystem(item).requirements;
  const caster = actor.conditionSelf ?? null;
  if (!caster || !Array.isArray(requirements) || !requirements.length) return { ok: true, failedNames: [] };
  const result = checkCaster({ requirements, caster, item: {} });
  return { ok: result.ok, failedNames: Object.freeze([...result.failedNames]) };
}

function acceptToggle(updates, field, enabled, notices = []) {
  return {
    ok: true,
    code: RESULT_CODES.INVENTORY_EQUIPMENT_UPDATED,
    updates,
    field,
    enabled,
    notices: Object.freeze([...notices])
  };
}

function refuseToggle(code, data = {}) {
  return Object.freeze({ ...data, ok: false, code, updates: Object.freeze([]) });
}

function dedupeUpdates(updates) {
  const byId = new Map();
  for (const update of updates) byId.set(update._id, { ...(byId.get(update._id) ?? {}), ...update });
  return [...byId.values()];
}
