/** @layer presentation/interface */
import { RESULT_CODES } from '../../contracts/results.mjs';
import { GUARD_BOND_REFUSALS } from '../../contracts/domains/combat.mjs';

/* -------------------------------------------- */
/*  Notification ids                            */
/* -------------------------------------------- */
/**
 * Every notification the system can show, by id. The text for each lives in notification-catalog.mjs, which takes
 * the downtime notices from downtime-notifications.mjs. Command result codes are notification ids too, because
 * NotificationService.showResult looks the catalog up by `result.code`. The ids added below are the system's other
 * notices. Sheets, menus and controls in ui/ raise most of them. The rest come from the BG3 HUD, the Guard bond and
 * class-feature presentations, init/system.mjs, the notifier factories in notifications.mjs, and the party and
 * authoring results, which return some of these ids as plain strings.
 */
export const NOTIFICATION_IDS = Object.freeze({
  ...RESULT_CODES,
  CLASS_FEATURE_GAINED: 'class.feature-gained',
  CLASS_FEATURES_REPLACED: 'class.features-replaced',
  CLASS_FEATURE_MISSING: 'class.feature-missing',
  INNATE_GRANT_SOURCE_MISSING: 'character.innate-grant-source-missing',
  CLASS_CATALOG_EMPTY: 'class.catalog-empty',
  CLASS_SELECTION_REQUIRED: 'class.selection-required',
  CLASS_TEMPLATE_UNAVAILABLE: 'class.template-unavailable',
  CLASS_SOURCE_NOT_FOUND: 'class.source-not-found',
  CLASS_UNIQUE_FEATURES_REMOVED: 'class.unique-features-removed',
  CLASS_NOT_ASSIGNED: 'class.not-assigned',
  CHARACTER_SHEET_INFO: 'character.sheet-info',
  CHARACTER_SHEET_WARNING: 'character.sheet-warning',
  INVENTORY_WARNING: 'inventory.warning',
  INVENTORY_ERROR: 'inventory.error',
  INVENTORY_TWO_HANDED_UNWIELDED: 'inventory.two-handed-unwielded',
  MOVEMENT_OUT_OF_AREA: 'movement.out-of-area',
  SUPPORT_WARNING: 'character.support.warning',
  /** A Guard bond that can't form is refused with a GUARD_BOND_REFUSALS code, so these ids reuse those codes. */
  GUARD_BOND_SELF: GUARD_BOND_REFUSALS.SELF,
  GUARD_BOND_HELD: GUARD_BOND_REFUSALS.GUARDER_BONDED,
  GUARD_BOND_PARTNER_HELD: GUARD_BOND_REFUSALS.GUARDED_BONDED,
  GUARD_BOND_OFF_MAP: GUARD_BOND_REFUSALS.OFF_MAP,
  GUARD_BOND_GROUNDED: GUARD_BOND_REFUSALS.GROUNDED,
  GUARD_BOND_SMALLER: GUARD_BOND_REFUSALS.SMALLER,
  GUARD_BOND_BROKEN: 'combat.guard-bond-broken',
  /** The GM's notice that an authored effect step or entry was skipped (engine/effects/execution.mjs). */
  EFFECT_STEP_SKIPPED: 'effect.step-skipped',
  COINPURSE_CARRIER_REQUIRED: 'economy.coinpurse-carrier-required',
  VENDOR_STOCK_EMPTY: 'vendor.stock-empty',
  VENDOR_STOCK_ALL_LOCKED: 'vendor.stock-all-locked',
  VENDOR_STOCK_CLEARED: 'vendor.stock-cleared',
  VENDOR_STOCK_CLEAR_FAILED: 'vendor.stock-clear-failed',
  STEAL_NOTHING_TO_TAKE: 'economy.nothing-to-take',
  TARGETING_WARNING: 'targeting.warning',
  COMBAT_PREVIEW_REFRESH_FAILED: 'combat-preview.refresh-failed',
  OBJECT_TOOL_PENDING: 'object.tool-pending',
  OBJECT_KEY_ITEM_TYPE: 'object.key-item-type',
  OBJECT_CONTENT_ITEM_TYPE: 'object.content-item-type',
  OBJECT_STANCE_BROKEN: 'object.stance-broken',
  TERRAIN_INFO: 'terrain.info',
  TERRAIN_WARNING: 'terrain.warning',
  ACTOR_CONTROL_COLOR_INVALID: 'actor-control.color-invalid',
  ACTOR_CONTROL_UPDATE_FAILED: 'actor-control.update-failed',
  ACTOR_CONTROL_INFO: 'actor-control.info',
  ACTOR_CONTROL_WARNING: 'actor-control.warning',
  ENCOUNTER_OBJECTIVE_WARNING: 'encounters.objective-warning',
  ENCOUNTER_PHASE_CHANGE_STOPPED: 'encounters.phase-change-stopped',
  ACTOR_CONTROL_STUDIO_ACTOR_REQUIRED: 'actor-control.studio-actor-required',
  ACTOR_CONTROL_STUDIO_BASE_ACTOR_REQUIRED: 'actor-control.studio-base-actor-required',
  ACTOR_CONTROL_STUDIO_SLOT_UNKNOWN: 'actor-control.studio-slot-unknown',
  ACTOR_CONTROL_STUDIO_TAB_NOT_FOUND: 'actor-control.studio-tab-not-found',
  ACTOR_CONTROL_STUDIO_ENTRY_NOT_FOUND: 'actor-control.studio-entry-not-found',
  ACTOR_CONTROL_STUDIO_UNAVAILABLE: 'actor-control.studio-unavailable',
  PARTY_ACTOR_IMPORT_REQUIRED: 'party.actor-import-required',
  PARTY_CHARACTER_REQUIRED: 'party.character-required',
  PARTY_DROP_ACTOR_REQUIRED: 'party.drop-actor-required',
  PARTY_OWNERSHIP_GRANTED: 'party.ownership-granted',
  PARTY_OWNERSHIP_GRANT_FAILED: 'party.ownership-grant-failed',
  PARTY_OWNERSHIP_REVOKE_FAILED: 'party.ownership-revoke-failed',
  PARTY_PLAYER_CHARACTER_SYNC_FAILED: 'party.player-character-sync-failed',
  PARTY_UNIT_TYPE_FAILED: 'party.unit-type-failed',
  PARTY_UNIT_ASSIGNMENT_FAILED: 'party.unit-assignment-failed',
  PARTY_UNIT_TYPE_CONFIRMATION_REQUIRED: 'party.unit-type-confirmation-required',
  FEATURE_TYPE_REQUIRED: 'authoring.feature-type-required',
  FEATURE_NOT_FOUND: 'authoring.feature-not-found',
  CLASS_MOUNT_EXISTS: 'authoring.class-mount-exists',
  PROMOTION_ITEM_REQUIRED: 'authoring.promotion-item-required',
  PROMOTION_CLASS_REQUIRED: 'authoring.promotion-class-required',
  ITEM_JSON_INVALID: 'authoring.item-json-invalid',
  ITEM_EDITOR_UNAVAILABLE: 'authoring.item-editor-unavailable',
  ITEM_EDITOR_INFO: 'authoring.item-editor-info',
  ITEM_EDITOR_WARNING: 'authoring.item-editor-warning',
  ITEM_EDITOR_ERROR: 'authoring.item-editor-error',
  ITEM_AUTHORING_DENIED: 'authoring.denied',
  STAFF_CREATED: 'authoring.staff-created',
  ITEM_NOT_FOUND: 'authoring.item-not-found',
  ITEM_DATABASE_REFINEMENT_FORBIDDEN: 'authoring.database-refinement-forbidden',
  ITEM_REFINEMENT_RESET: 'authoring.refinement-reset',
  ITEM_REFINEMENT_REVERTED: 'authoring.refinement-reverted',
  ITEM_REFINEMENT_BASE_MISSING: 'authoring.refinement-base-missing',
  SCENE_GRIDLESS_BLOCKED: 'scene.gridless-blocked',
  TOKEN_SIZE_INVALID: 'token.size-invalid',
  SCENE_REFERENCES_REPAIRED: 'scene.references-repaired',
  WORLD_SCHEMA_MISMATCH: 'world.schema-mismatch',
  WORLD_MIGRATION_STARTED: 'world.migration-started',
  WORLD_MIGRATION_COMPLETED: 'world.migration-completed',
  WORLD_MIGRATION_CONFLICTS: 'world.migration-conflicts',
  WORLD_MIGRATION_INCOMPLETE: 'world.migration-incomplete',
  WORLD_MIGRATION_FAILED: 'world.migration-failed',
  STARTUP_FAILED: 'world.startup-failed',
  TABLE_COMMAND_GM_ONLY: 'table.command-gm-only',
  TABLE_COMMAND_USAGE: 'table.command-usage',
  TABLE_COMMAND_INFO: 'table.command-info',
  TABLE_COMMAND_FAILED: 'table.command-failed',
  BG3_NO_ACTOR: 'bg3-hud.no-actor',
  BG3_PERSISTENCE_UNAVAILABLE: 'bg3-hud.persistence-unavailable',
  BG3_AUTO_POPULATE_UNAVAILABLE: 'bg3-hud.auto-populate-unavailable',
  BG3_HOTBAR_COMPLETE: 'bg3-hud.hotbar-complete',
  BG3_RESYNC_SELECT_TOKEN: 'bg3-hud.resync-select-token',
  BG3_RESYNC_NOT_OWNED: 'bg3-hud.resync-not-owned',
  BG3_INSPECTING_UNIT: 'bg3-hud.inspecting-unit',
  ENCOUNTER_SCENE_REQUIRED: 'encounter.scene-required'
});
