/** @layer ui */

/* -------------------------------------------- */
/*  Tooltip catalog                             */
/* -------------------------------------------- */
export const TOOLTIP_IDS = Object.freeze({
  RESTORE_STANDARD_ACTION: 'character.restore-standard-action',
  SPEND_STANDARD_ACTION: 'character.spend-standard-action',
  STANDARD_ACTION_SPENT: 'character.standard-action-spent',
  OPEN_ACTOR_CONTROL: 'character.open-actor-control',
  SKILL: 'character.skill',
  PROFICIENCY: 'character.proficiency',
  STAT_PENALTY: 'character.stat-penalty',
  OPEN_ITEM: 'character.open-item',
  REMOVE_PASSIVE: 'character.remove-passive',
  TOGGLE_UNIT_TYPE: 'character.toggle-unit-type',
  TOGGLE_INVENTORY_SORT: 'character.toggle-inventory-sort',
  SORT_DIRECTION: 'character.sort-direction',
  INVENTORY_TAB: 'character.inventory-tab',
  DRAG_ITEM: 'character.drag-item',
  DROP_ITEM: 'character.drop-item',
  DELETE_ITEM: 'character.delete-item',
  INNATE_ITEM: 'character.innate-item',
  EXTRA_LIFE: 'character.extra-life',
  ADJUST_SPECIAL_MAX: 'character.adjust-special-max',
  OPEN_LINKED_CONVOY: 'character.open-linked-convoy',
  OPEN_JOURNAL: 'character.open-journal',
  UNLINK_JOURNAL: 'character.unlink-journal',
  OPEN_RECIPE: 'character.open-recipe',
  UNLINK_RECIPE: 'character.unlink-recipe',
  OPEN_SONG: 'character.open-song',
  UNLINK_SONG: 'character.unlink-song',
  ADD_SUPPORT: 'character.add-support',
  REMOVE_SUPPORT: 'character.remove-support',
  SUPPORT_CARD: 'character.support-card'
});

export const SHEET_TOOLTIP_IDS = Object.freeze({
  EDIT_IMAGE: 'sheet.edit-image',
  EDIT_ANIMATIONS: 'sheet.edit-animations',
  EDIT: 'sheet.edit',
  DELETE: 'sheet.delete',
  OPEN: 'sheet.open',
  REMOVE_VENDOR_ITEM: 'vendor.remove-item',
  LINK_VENDOR_ACTOR: 'vendor.link-actor',
  SHOP_PREVIEW: 'vendor.shop-preview',
  SHOP_ADD_TO_CART: 'vendor.shop-add-to-cart',
  SHOP_UNACCEPTED: 'vendor.shop-unaccepted',
  SHOP_SOLD_HERE: 'vendor.shop-sold-here',
  SHOP_ADD_ONE: 'vendor.shop-add-one',
  SHOP_REMOVE_ONE: 'vendor.shop-remove-one',
  SHOP_QUANTITY: 'vendor.shop-quantity',
  SHOP_DISPOSITION: 'vendor.shop-disposition',
  SHOP_DISPOSITION_HAGGLED: 'vendor.shop-disposition-haggled',
  SHOP_HAGGLE_LOCKED: 'vendor.shop-haggle-locked',
  SHOP_HAGGLE_OUTSIDE_ROSTER: 'vendor.shop-haggle-outside-roster',
  SHOP_SORT_FIELD: 'vendor.shop-sort-field',
  SHOP_SORT_ASCENDING: 'vendor.shop-sort-ascending',
  SHOP_SORT_DESCENDING: 'vendor.shop-sort-descending',
  COOK_CHEF_EATS: 'cooking.chef-eats',
  NEW_RECIPE: 'recipe.new',
  RECIPE_GROWTH: 'recipe.growth',
  RESTORE_BUILTINS: 'recipe.restore-builtins',
  LINK_RECIPE: 'recipe.link',
  CHANGE_RECIPE_IMAGE: 'recipe.change-image',
  RECIPE_DIFFICULTY: 'recipe.difficulty',
  NEW_SONG: 'song.new',
  SONG_BONUS: 'song.bonus',
  RESTORE_BUILTIN_SONGS: 'song.restore-builtins',
  LINK_SONG: 'song.link',
  CHANGE_SONG_IMAGE: 'song.change-image',
  SONG_DIFFICULTY: 'song.difficulty',
  SONG_PERFORMERS: 'song.performers',
  SONG_TRACK: 'song.track',
  REQUISITION_DEMAND: 'requisition.demand',
  REQUISITION_DC: 'requisition.dc',
  REQUISITION_CONVOY: 'requisition.convoy',
  DRAG_GOLD: 'convoy.drag-gold',
  CONVOY_VIEW_STORED: 'convoy.view-stored',
  CONVOY_VIEW_INBOUND: 'convoy.view-inbound',
  CONVOY_DELIVER_ALL: 'convoy.deliver-all',
  CONVOY_INBOUND_GOLD: 'convoy.inbound-gold',
  CONVOY_INBOUND_GOLD_STAFF: 'convoy.inbound-gold-staff',
  CONVOY_INBOUND_ITEM: 'convoy.inbound-item',
  CONVOY_INBOUND_ITEM_STAFF: 'convoy.inbound-item-staff',
  DROP_ITEM: 'trade.drop-item',
  CLEAR_KEY: 'object.clear-key',
  PICK_STATE_IMAGE: 'object.pick-state-image',
  TOKEN_LINK: 'object.token-link',
  TOKEN_SIZE: 'object.token-size',
  IMAGE_SCALE: 'object.image-scale',
  TOKEN_TINT: 'object.token-tint',
  STATE_SCALE: 'object.state-scale',
  STATE_TINT: 'object.state-tint',
  STATE_OFFSET_X: 'object.state-offset-x',
  STATE_OFFSET_Y: 'object.state-offset-y',
  BLOCK_FLYERS: 'object.block-flyers',
  ATTACK_STAT: 'object.attack-stat',
  TOGGLE_EXTRA_ATTACKS: 'object.toggle-extra-attacks',
  DRAG_EFFECT: 'object.drag-effect',
  GATHER_MULTIPLIER: 'object.gather-multiplier',
  GATHER_TOTAL: 'object.gather-total',
  GATHER_WEIGHT: 'object.gather-weight',
  GATHER_HIDDEN: 'object.gather-hidden',
  REMOVE_GATHERABLE: 'object.remove-gatherable',
  REMOVE_BOON: 'object.remove-boon',
  FACTION_NAME: 'object.faction-name',
  FACTION_RELATION: 'object.faction-relation',
  FACTION_WEALTH: 'object.faction-wealth',
  FACTION_ENABLED: 'object.faction-enabled',
  FACTION_REQUISITIONED: 'object.faction-requisitioned',
  CLEAR_FACTION_LOCK: 'object.clear-faction-lock',
  REMOVE_FACTION: 'object.remove-faction',
  PROFICIENCY: 'object.proficiency',
  RANK: 'object.rank',
  FEATURE_UNAVAILABLE: 'object.feature-unavailable'
});

const CLASS_TOOLTIP_IDS = Object.freeze({
  EDIT_IMAGE: 'class.edit-image',
  UNIQUE_FEATURES: 'class.unique-features',
  EDIT_FEATURE_BUNDLE: 'class.edit-feature-bundle',
  DELETE_FEATURE_BUNDLE: 'class.delete-feature-bundle',
  REMOVE_REPLACED_FEATURE: 'class.remove-replaced-feature',
  REQUIRES_REPLACED_FEATURE: 'class.requires-replaced-feature',
  ALREADY_UNLOCKED: 'class.already-unlocked',
  SKIPPED_UPGRADE: 'class.skipped-upgrade',
  BUNDLE_REPLACE: 'class.bundle-replace',
  BUNDLE_UNIQUE: 'class.bundle-unique',
  BUNDLE_EXCEPTIONS: 'class.bundle-exceptions',
  EDIT_PROMOTION: 'class.edit-promotion',
  DELETE_PROMOTION: 'class.delete-promotion'
});

export const PARTY_TOOLTIP_IDS = Object.freeze({
  ADD_BY_UUID: 'party.add-by-uuid',
  COLLAPSE_PLAYER: 'party.collapse-player',
  DELETE_PARTY: 'party.delete-party',
  EXPAND_PLAYER: 'party.expand-player',
  REMOVE_UNIT: 'party.remove-unit',
  RENAME_PARTY: 'party.rename-party',
  UNLINK_CONVOY: 'party.unlink-convoy'
});

export const ACTOR_CONTROL_TOOLTIP_IDS = Object.freeze({
  AUDIO_TRAY: 'actor-control.audio-tray',
  APPROVE_VOICE_PATH: 'actor-control.approve-voice-path',
  APPROVED_VOICE_PATH: 'actor-control.approved-voice-path',
  BROWSE_AUDIO_FOLDER: 'actor-control.browse-audio-folder',
  BROWSE_FACTION_ICON: 'actor-control.browse-faction-icon',
  FACTION_TRAY: 'actor-control.faction-tray',
  CLEAR_TOKEN_IMAGE: 'actor-control.clear-token-image',
  EDIT_TOKEN_IMAGE: 'actor-control.edit-token-image',
  ADD_TOKEN_TAB: 'actor-control.add-token-tab',
  FILL_TOKEN_TABS: 'actor-control.fill-token-tabs',
  RENAME_TOKEN_TAB: 'actor-control.rename-token-tab',
  DELETE_TOKEN_TAB: 'actor-control.delete-token-tab',
  TOKEN_OFFSET_Y: 'actor-control.token-offset-y',
  ADD_CONDITIONAL_ENTRY: 'actor-control.add-conditional-entry',
  MAP_CONDITIONAL_ENTRIES: 'actor-control.map-conditional-entries',
  DRAG_CONDITIONAL_ENTRY: 'actor-control.drag-conditional-entry',
  ADD_TRIGGER: 'actor-control.add-trigger',
  REMOVE_TRIGGER: 'actor-control.remove-trigger',
  ADD_REQUIREMENT: 'actor-control.add-requirement',
  REMOVE_REQUIREMENT: 'actor-control.remove-requirement',
  SPECIFIC_ITEM: 'actor-control.specific-item',
  SPECIFIC_ABILITY: 'actor-control.specific-ability',
  SPECIFIC_SPELL: 'actor-control.specific-spell',
  DROP_ITEM: 'actor-control.drop-item',
  DUPLICATE_ENTRY: 'actor-control.duplicate-entry',
  DELETE_ENTRY: 'actor-control.delete-entry',
  PICK_COLOR: 'actor-control.pick-color',
  TOKEN_SCALE: 'actor-control.token-scale',
  UNLINKED_TOKEN: 'actor-control.unlinked-token'
});

export const ENCOUNTER_TOOLTIP_IDS = Object.freeze({
  AUTO_ADVANCE: 'encounter.auto-advance',
  COMBAT_MUSIC: 'encounter.combat-music',
  PLAYER_PHASE_TRACK: 'encounter.player-phase-track',
  ENEMY_PHASE_TRACK: 'encounter.enemy-phase-track',
  PHASE_PROGRESS: 'encounter.phase-progress',
  SORT_FIELD: 'encounter.sort-field',
  SORT_DIRECTION: 'encounter.sort-direction',
  PREVIOUS_PAGE: 'encounter.previous-page',
  NEXT_PAGE: 'encounter.next-page',
  OBJECTIVE_TARGET: 'encounter.objective-target',
  PROTECTED_UNIT: 'encounter.protected-unit',
  ARRIVED_UNIT: 'encounter.arrived-unit',
  LORD_UNIT: 'encounter.lord-unit',
  EMITTING_AURA: 'encounter.emitting-aura',
  SET_OBJECTIVES: 'encounter.set-objectives',
  EDIT_OBJECTIVES: 'encounter.edit-objectives',
  BEGIN_ENCOUNTER: 'encounter.begin',
  CANCEL_ENCOUNTER: 'encounter.cancel',
  END_SUCCESS: 'encounter.end-success',
  END_FAILURE: 'encounter.end-failure',
  PAUSE_ENCOUNTER: 'encounter.pause',
  RESUME_ENCOUNTER: 'encounter.resume',
  DISCARD_PAUSE: 'encounter.discard-pause',
  END_MENU_BACK: 'encounter.end-menu-back',
  RESET_DOWNTIME: 'encounter.reset-downtime'
});

export const SCENE_TOOLTIP_IDS = Object.freeze({
  MAP_VISIBLE: 'scene.map-visible',
  MOVEMENT_PERMISSION: 'scene.movement-permission',
  MOVE_SCALING: 'scene.move-scaling',
  TOKEN_OUTLINE_RESET: 'scene.token-outline-reset'
});

const TOOLTIPS = Object.freeze({
  // Character
  [TOOLTIP_IDS.RESTORE_STANDARD_ACTION]: 'Restore this character\'s standard action',
  [TOOLTIP_IDS.SPEND_STANDARD_ACTION]: 'Spend this character\'s standard action',
  [TOOLTIP_IDS.STANDARD_ACTION_SPENT]: 'This character already spent their standard action',
  [TOOLTIP_IDS.OPEN_ACTOR_CONTROL]: 'Open this character\'s Actor Control Panel',
  [TOOLTIP_IDS.SKILL]: ({ label, rankLabel }) => `${label}${rankLabel ? ` (${rankLabel})` : ''}`,
  [TOOLTIP_IDS.PROFICIENCY]: ({ label }) => label,
  [TOOLTIP_IDS.STAT_PENALTY]: ({ key, label }) => `${key === 'mov' ? 'Movement' : label} penalty`,
  [TOOLTIP_IDS.OPEN_ITEM]: 'Open this item',
  [TOOLTIP_IDS.REMOVE_PASSIVE]: 'Remove this passive feature',
  [TOOLTIP_IDS.TOGGLE_UNIT_TYPE]: ({ label }) => `${label}`,
  [TOOLTIP_IDS.TOGGLE_INVENTORY_SORT]: 'Toggle sort field',
  [TOOLTIP_IDS.SORT_DIRECTION]: ({ direction }) => (direction === 'asc' ? 'Ascending' : 'Descending'),
  [TOOLTIP_IDS.INVENTORY_TAB]: ({ key, title, page }) => {
    const base = key.startsWith('equipment') ? 'Gear'
      : key.startsWith('spells') ? 'Spells'
      : key.startsWith('abilities') ? 'Abilities' : title;
    return page ? `${base} (page ${page})` : base;
  },
  [TOOLTIP_IDS.DRAG_ITEM]: ({ name, destination }) => `${name} (${destination})`,
  [TOOLTIP_IDS.DROP_ITEM]: 'Drop Item',
  [TOOLTIP_IDS.DELETE_ITEM]: ({ type }) => (type === 'Spell' ? 'Delete Spell' : 'Delete Item'),
  [TOOLTIP_IDS.INNATE_ITEM]: 'Innate feature',
  [TOOLTIP_IDS.EXTRA_LIFE]: ({ index }) => `Extra Life ${Number(index) + 1}`,
  [TOOLTIP_IDS.ADJUST_SPECIAL_MAX]: ({ delta, label }) => `${delta > 0 ? 'Increase' : 'Decrease'} max ${label}`,
  [TOOLTIP_IDS.OPEN_LINKED_CONVOY]: 'Open Linked Convoy',
  [TOOLTIP_IDS.OPEN_JOURNAL]: 'Open this journal entry',
  [TOOLTIP_IDS.UNLINK_JOURNAL]: 'Unlink journal entry',
  [TOOLTIP_IDS.OPEN_RECIPE]: data => `${data?.growths ? `${data.growths}` : ''}`,
  [TOOLTIP_IDS.UNLINK_RECIPE]: 'Unlink recipe',
  [TOOLTIP_IDS.OPEN_SONG]: data => `${data?.bonuses ? `${data.bonuses}` : ''}`,
  [TOOLTIP_IDS.UNLINK_SONG]: 'Unlink song',
  [TOOLTIP_IDS.ADD_SUPPORT]: 'Add support',
  [TOOLTIP_IDS.REMOVE_SUPPORT]: 'Remove support',
  [TOOLTIP_IDS.SUPPORT_CARD]: ({ name, rankLetter, xp, xpNeeded }) => `${name} Rank ${rankLetter} (${xp}/${xpNeeded})`,

  // Object, Convoy and Vendor sheets, and the shop, trade and downtime menus
  [SHEET_TOOLTIP_IDS.EDIT_IMAGE]: 'Edit image',
  [SHEET_TOOLTIP_IDS.EDIT_ANIMATIONS]: 'Edit animations',
  [SHEET_TOOLTIP_IDS.EDIT]: 'Edit',
  [SHEET_TOOLTIP_IDS.DELETE]: 'Delete',
  [SHEET_TOOLTIP_IDS.DROP_ITEM]: 'Drop or discard',
  [SHEET_TOOLTIP_IDS.OPEN]: 'Open',
  [SHEET_TOOLTIP_IDS.REMOVE_VENDOR_ITEM]: 'Remove from vendor',
  [SHEET_TOOLTIP_IDS.SHOP_PREVIEW]: 'Preview this item',
  [SHEET_TOOLTIP_IDS.SHOP_ADD_TO_CART]: 'Add to Cart',
  [SHEET_TOOLTIP_IDS.SHOP_UNACCEPTED]: "This merchant won't buy this",
  [SHEET_TOOLTIP_IDS.SHOP_SOLD_HERE]: "This merchant won't buy back what it sold",
  [SHEET_TOOLTIP_IDS.SHOP_ADD_ONE]: 'Add one',
  [SHEET_TOOLTIP_IDS.SHOP_REMOVE_ONE]: 'Remove one',
  [SHEET_TOOLTIP_IDS.SHOP_QUANTITY]: ({ max }) => `Quantity (max ${max ?? 0})`,
  [SHEET_TOOLTIP_IDS.SHOP_DISPOSITION]: 'Higher disposition means better prices',
  [SHEET_TOOLTIP_IDS.SHOP_DISPOSITION_HAGGLED]: ({ bonus }) => {
    const value = Number(bonus) || 0;
    return `Higher disposition means better prices | Haggle: ${value > 0 ? '+' : ''}${value}`;
  },
  [SHEET_TOOLTIP_IDS.SHOP_HAGGLE_LOCKED]: 'Already haggled this downtime',
  [SHEET_TOOLTIP_IDS.SHOP_HAGGLE_OUTSIDE_ROSTER]: 'Lords and Retainers only',
  [SHEET_TOOLTIP_IDS.SHOP_SORT_FIELD]: 'Toggle sort field',
  [SHEET_TOOLTIP_IDS.SHOP_SORT_ASCENDING]: 'Ascending',
  [SHEET_TOOLTIP_IDS.SHOP_SORT_DESCENDING]: 'Descending',
  [SHEET_TOOLTIP_IDS.COOK_CHEF_EATS]: 'The chef always eats',
  [SHEET_TOOLTIP_IDS.NEW_RECIPE]: data => `New ${data?.tab ?? ''} recipe`,
  [SHEET_TOOLTIP_IDS.RECIPE_GROWTH]: data => `${data?.label ?? ''} growth rate bonus (percentage points)`,
  [SHEET_TOOLTIP_IDS.RESTORE_BUILTINS]: 'Restore the system’s built-in recipes',
  [SHEET_TOOLTIP_IDS.LINK_RECIPE]: 'Drag onto a unit’s sheet to teach them this recipe',
  [SHEET_TOOLTIP_IDS.CHANGE_RECIPE_IMAGE]: 'Change image',
  [SHEET_TOOLTIP_IDS.RECIPE_DIFFICULTY]: 'Nature check difficulty',
  [SHEET_TOOLTIP_IDS.NEW_SONG]: data => `New ${data?.tab ?? ''} song`,
  [SHEET_TOOLTIP_IDS.SONG_BONUS]: data => `${data?.label ?? ''} bonus every listener gains (0 to 10)`,
  [SHEET_TOOLTIP_IDS.RESTORE_BUILTIN_SONGS]: 'Restore the system’s built-in songs',
  [SHEET_TOOLTIP_IDS.LINK_SONG]: 'Drag onto a unit’s sheet to teach them this song',
  [SHEET_TOOLTIP_IDS.CHANGE_SONG_IMAGE]: 'Change image',
  [SHEET_TOOLTIP_IDS.SONG_DIFFICULTY]: 'Performance check difficulty for every performer',
  [SHEET_TOOLTIP_IDS.SONG_PERFORMERS]: 'How many units perform it',
  [SHEET_TOOLTIP_IDS.SONG_TRACK]: 'Music the table hears while the song is performed',
  [SHEET_TOOLTIP_IDS.REQUISITION_DEMAND]: 'Gold to ask for',
  [SHEET_TOOLTIP_IDS.REQUISITION_DC]: 'Base DC plus 1 per 100 GP demanded',
  [SHEET_TOOLTIP_IDS.REQUISITION_CONVOY]: 'Where the gold goes on a success',
  [SHEET_TOOLTIP_IDS.LINK_VENDOR_ACTOR]: 'Link the prototype token so placed tokens share this actor',
  [SHEET_TOOLTIP_IDS.DRAG_GOLD]: 'Drag onto a unit to hand out gold',
  [SHEET_TOOLTIP_IDS.CONVOY_VIEW_STORED]: 'Show what the Convoy holds',
  [SHEET_TOOLTIP_IDS.CONVOY_VIEW_INBOUND]: 'Show the gold and items on their way to the Convoy',
  [SHEET_TOOLTIP_IDS.CONVOY_DELIVER_ALL]: 'Deliver every inbound item and all inbound gold into the Convoy',
  [SHEET_TOOLTIP_IDS.CONVOY_INBOUND_GOLD]: 'Gold on its way to the Convoy',
  [SHEET_TOOLTIP_IDS.CONVOY_INBOUND_GOLD_STAFF]: 'Gold on its way to the Convoy',
  [SHEET_TOOLTIP_IDS.CONVOY_INBOUND_ITEM]: 'On its way to the Convoy',
  [SHEET_TOOLTIP_IDS.CONVOY_INBOUND_ITEM_STAFF]: 'On its way to the Convoy',
  [SHEET_TOOLTIP_IDS.CLEAR_KEY]: 'Clear key',
  [SHEET_TOOLTIP_IDS.PICK_STATE_IMAGE]: 'Image for this state',
  [SHEET_TOOLTIP_IDS.TOKEN_LINK]: 'Link the token to this actor, '
    + 'so every placed copy shares its data',
  [SHEET_TOOLTIP_IDS.TOKEN_SIZE]: 'Token size (grid squares)',
  [SHEET_TOOLTIP_IDS.IMAGE_SCALE]: 'Image scale',
  [SHEET_TOOLTIP_IDS.TOKEN_TINT]: 'Token tint',
  [SHEET_TOOLTIP_IDS.STATE_SCALE]: 'Image scale in this state',
  [SHEET_TOOLTIP_IDS.STATE_TINT]: 'Token tint in this state',
  [SHEET_TOOLTIP_IDS.STATE_OFFSET_X]: 'Horizontal sprite offset (px) in this state',
  [SHEET_TOOLTIP_IDS.STATE_OFFSET_Y]: 'Vertical sprite offset (px) in this state',
  [SHEET_TOOLTIP_IDS.BLOCK_FLYERS]: 'Blocks flyers while intact',
  [SHEET_TOOLTIP_IDS.ATTACK_STAT]: 'Attacks receive a damage bonus from this stat',
  [SHEET_TOOLTIP_IDS.TOGGLE_EXTRA_ATTACKS]: 'Disable extra attacks',
  [SHEET_TOOLTIP_IDS.DRAG_EFFECT]: 'Drag to reorder',
  [SHEET_TOOLTIP_IDS.GATHER_MULTIPLIER]: 'Units gathered = skill roll × this',
  [SHEET_TOOLTIP_IDS.GATHER_TOTAL]: 'How many of this resource the node holds',
  [SHEET_TOOLTIP_IDS.GATHER_WEIGHT]: 'Drop weight: 0.1 (rare) to 1 (common)',
  [SHEET_TOOLTIP_IDS.GATHER_HIDDEN]: 'Hidden gatherables show as unknown in the menu',
  [SHEET_TOOLTIP_IDS.REMOVE_GATHERABLE]: 'Remove gatherable',
  [SHEET_TOOLTIP_IDS.REMOVE_BOON]: 'Remove boon',
  [SHEET_TOOLTIP_IDS.FACTION_NAME]: 'The faction’s name, as the Requisition menu lists it',
  [SHEET_TOOLTIP_IDS.FACTION_RELATION]: 'How the faction regards the party',
  [SHEET_TOOLTIP_IDS.FACTION_WEALTH]: 'The most gold the faction sends for one requisition',
  [SHEET_TOOLTIP_IDS.FACTION_ENABLED]: 'Offer this faction in the Requisition menu',
  [SHEET_TOOLTIP_IDS.FACTION_REQUISITIONED]: 'A unit requisitioned this faction this downtime',
  [SHEET_TOOLTIP_IDS.CLEAR_FACTION_LOCK]: 'Unlock this faction for another requisition',
  [SHEET_TOOLTIP_IDS.REMOVE_FACTION]: 'Remove faction',
  [SHEET_TOOLTIP_IDS.PROFICIENCY]: 'Proficiency',
  [SHEET_TOOLTIP_IDS.RANK]: 'Rank',
  [SHEET_TOOLTIP_IDS.FEATURE_UNAVAILABLE]: 'This feature is not yet available',

  // Terrain Builder
  'terrain.add-to-zone': 'Add selected squares to this zone',
  'terrain.advanced': 'Advanced settings',
  'terrain.all-directions': 'All Directions',
  'terrain.audio': 'Audio',
  'terrain.blockable': 'Blocks use while a unit stands on the far square',
  'terrain.copy': "Copy this tile's parameters",
  'terrain.crossing-dc': 'DC = This * Elev Difference',
  'terrain.geography': 'Geography',
  'terrain.light': 'Light',
  'terrain.mechanics': 'Mechanical effects',
  'terrain.new-zone': 'Create a zone from the selected squares',
  'terrain.objective': 'What this square does as an objective point',
  'terrain.overview': 'Everything saved to this square',
  'terrain.overview-jump': 'Open the tray that sets this',
  'terrain.overview-toggle': 'Turn this flag off',
  'terrain.paste': 'Paste copied parameters into the form',
  'terrain.remove-edit': 'Remove this persisted effect and revert the square',
  'terrain.select-zone': "Select this zone's squares",
  'terrain.stats': 'Stat modifiers',
  'terrain.visual-fx': 'Visual FX',
  'terrain.wall-attenuation': 'Light and sound fade out toward the threshold',
  'terrain.wall-bone-length': 'Pixels each freestyle wall runs before the next one starts',
  'terrain.wall-clear': 'Delete every wall on this scene except Door walls',
  'terrain.wall-ethereal': 'Blocks sight and light only',
  'terrain.wall-invisible': 'Blocks movement only',
  'terrain.wall-sense': 'Limited passes the first limited wall | Proximity passes within the threshold | Distance passes beyond it',
  'terrain.wall-solid': 'Blocks movement, sight, light and sound',
  'terrain.wall-terrain': 'Blocks movement | sight, light and sound pass the first limited wall',
  'terrain.wall-threshold': 'Squares from the wall for Proximity and Distance',
  'terrain.wall-window': 'Blocks movement and sound | sight and light pass within 2 squares',
  'terrain.zone-cells': 'Squares in this zone',

  // Class sheet
  [CLASS_TOOLTIP_IDS.EDIT_IMAGE]: ({ name }) => `${name ?? 'Class'}`,
  [CLASS_TOOLTIP_IDS.UNIQUE_FEATURES]: ({ exceptions }) =>
    `Removed on class change${exceptions ? `, except to ${exceptions}` : ''}`,
  [CLASS_TOOLTIP_IDS.EDIT_FEATURE_BUNDLE]: 'Edit feature bundle',
  [CLASS_TOOLTIP_IDS.DELETE_FEATURE_BUNDLE]: 'Delete feature bundle',
  [CLASS_TOOLTIP_IDS.REMOVE_REPLACED_FEATURE]: ({ replaceName }) =>
    `Granting this removes ${replaceName ?? 'the replaced feature'}`,
  [CLASS_TOOLTIP_IDS.REQUIRES_REPLACED_FEATURE]: ({ replaceName }) =>
    `Requires ${replaceName || 'the feature this replaces'}`,
  [CLASS_TOOLTIP_IDS.ALREADY_UNLOCKED]: 'Already Unlocked',
  [CLASS_TOOLTIP_IDS.SKIPPED_UPGRADE]: ({ replaceName }) =>
    `Not granted: requires ${replaceName || 'the feature this replaces'}`,
  [CLASS_TOOLTIP_IDS.BUNDLE_REPLACE]: 'Required on the unit, and replaced when this is granted',
  [CLASS_TOOLTIP_IDS.BUNDLE_UNIQUE]: 'Removed from the unit when it changes class',
  [CLASS_TOOLTIP_IDS.BUNDLE_EXCEPTIONS]: 'Classes that keep these features on a class change',
  [CLASS_TOOLTIP_IDS.EDIT_PROMOTION]: 'Edit promotion',
  [CLASS_TOOLTIP_IDS.DELETE_PROMOTION]: 'Delete promotion',

  // Party configuration
  [PARTY_TOOLTIP_IDS.ADD_BY_UUID]: 'Add a unit by UUID',
  [PARTY_TOOLTIP_IDS.COLLAPSE_PLAYER]: ({ name }) => `Collapse ${name}`,
  [PARTY_TOOLTIP_IDS.DELETE_PARTY]: 'Delete party',
  [PARTY_TOOLTIP_IDS.EXPAND_PLAYER]: ({ name }) => `Expand ${name}`,
  [PARTY_TOOLTIP_IDS.REMOVE_UNIT]: 'Remove',
  [PARTY_TOOLTIP_IDS.RENAME_PARTY]: 'Rename party',
  [PARTY_TOOLTIP_IDS.UNLINK_CONVOY]: 'Unlink convoy',

  // Actor Control Panel
  [ACTOR_CONTROL_TOOLTIP_IDS.AUDIO_TRAY]: 'Audio',
  [ACTOR_CONTROL_TOOLTIP_IDS.APPROVE_VOICE_PATH]: 'Approve this folder for player voice lines',
  [ACTOR_CONTROL_TOOLTIP_IDS.APPROVED_VOICE_PATH]: 'Approved for player voice lines',
  [ACTOR_CONTROL_TOOLTIP_IDS.BROWSE_AUDIO_FOLDER]: 'Browse for an audio folder',
  [ACTOR_CONTROL_TOOLTIP_IDS.BROWSE_FACTION_ICON]: 'Browse for a faction icon',
  [ACTOR_CONTROL_TOOLTIP_IDS.FACTION_TRAY]: 'Faction',
  [ACTOR_CONTROL_TOOLTIP_IDS.CLEAR_TOKEN_IMAGE]: 'Clear image',
  [ACTOR_CONTROL_TOOLTIP_IDS.EDIT_TOKEN_IMAGE]: ({ label }) => `Choose the ${label.toLowerCase()} image`,
  [ACTOR_CONTROL_TOOLTIP_IDS.ADD_TOKEN_TAB]: 'Add a Class',
  [ACTOR_CONTROL_TOOLTIP_IDS.FILL_TOKEN_TABS]: "Add a tab for each promotion option in this actor's Class",
  [ACTOR_CONTROL_TOOLTIP_IDS.RENAME_TOKEN_TAB]: 'Rename tab',
  [ACTOR_CONTROL_TOOLTIP_IDS.DELETE_TOKEN_TAB]: 'Delete tab',
  [ACTOR_CONTROL_TOOLTIP_IDS.TOKEN_OFFSET_Y]: 'Vertical render offset in grid units, −0.5 to 1',
  [ACTOR_CONTROL_TOOLTIP_IDS.ADD_CONDITIONAL_ENTRY]: 'Add a blank conditional entry',
  [ACTOR_CONTROL_TOOLTIP_IDS.MAP_CONDITIONAL_ENTRIES]: 'Add the stock evade, attack and crit entries for the weapon types you check',
  [ACTOR_CONTROL_TOOLTIP_IDS.DRAG_CONDITIONAL_ENTRY]: 'Drag to reorder (top match wins)',
  [ACTOR_CONTROL_TOOLTIP_IDS.ADD_TRIGGER]: 'Add a trigger condition',
  [ACTOR_CONTROL_TOOLTIP_IDS.REMOVE_TRIGGER]: 'Remove trigger',
  [ACTOR_CONTROL_TOOLTIP_IDS.ADD_REQUIREMENT]: 'Add a requirement condition',
  [ACTOR_CONTROL_TOOLTIP_IDS.REMOVE_REQUIREMENT]: 'Remove requirement',
  [ACTOR_CONTROL_TOOLTIP_IDS.SPECIFIC_ITEM]: "Item names for 'Wielding: Specific Item'",
  [ACTOR_CONTROL_TOOLTIP_IDS.SPECIFIC_ABILITY]:
    "Ability names for 'Using Ability' (blank fires for every Active ability)",
  [ACTOR_CONTROL_TOOLTIP_IDS.SPECIFIC_SPELL]: "Spell names for this 'On Cast' pose (blank fires for every cast)",
  [ACTOR_CONTROL_TOOLTIP_IDS.DROP_ITEM]: 'Type Item names, comma-separated, or drag Items from the sidebar',
  [ACTOR_CONTROL_TOOLTIP_IDS.DUPLICATE_ENTRY]: 'Duplicate this entry: triggers, requirements and art',
  [ACTOR_CONTROL_TOOLTIP_IDS.DELETE_ENTRY]: 'Remove this entry',
  [ACTOR_CONTROL_TOOLTIP_IDS.PICK_COLOR]: 'Pick color',
  [ACTOR_CONTROL_TOOLTIP_IDS.TOKEN_SCALE]: 'Token Scale',
  [ACTOR_CONTROL_TOOLTIP_IDS.UNLINKED_TOKEN]: 'Open the base actor to edit shared token images',

  // Item sheet and item editors
  'item.click-to-edit-uses-parameters': "Edit uses parameters",
  'item.maximum-uses-scaled-edit-via-the-uses-label': "Maximum uses (scaled)",
  'item.uses-type-edit-via-the-uses-label': "Uses type",
  'item.if-checked-this-item-s-remaining-uses-will-refresh-at-the-st':
    "If checked, this item's remaining uses will refresh at the start of every map",
  'item.the-weapon-durability-cost-of-this-ability': "The weapon durability cost of this ability",
  'item.potions-always-target-self': "Potions always target Self",
  'item.boosters-always-target-self': "Boosters always target Self",
  'item.booster-stats': "Stats to raise, comma-separated: HP, Stn, Mov, Bld, Mgt, Agi, Tqn, Wit, Cha, Def, Res",
  'item.booster-stat-value': "Added to each listed stat, never past the class cap",
  'item.booster-growths': "Growths to raise, comma-separated: HP, Mgt, Agi, Tqn, Wit, Cha, Def, Res",
  'item.booster-growth-value': "Added to each listed growth rate",
  'item.click-to-edit-target-parameters': "Edit target parameters",
  'item.retractable': 'The unit may retract this action by pressing the Unselect/Cancel keybind.',
  'item.click-to-edit-range-scaling': "Edit range scaling",
  'item.effect-size-at-the-target-location': "Effect size at the target location",
  'item.attacks-receive-a-damage-bonus-from-this-stat': "Attacks receive a damage bonus from this stat",
  'item.what-this-item-s-range-ignores-when-checking-line-of-sight': "What this item's range ignores when checking line of sight",
  'item.click-to-edit-per-damage-type-conditions': "Edit per-damage-type conditions",
  'item.monstrosity': "Monstrosity",
  'item.click-toggle-grey-off-red-on': "Disable extra attacks",
  'item.drag-to-reorder': "Drag to reorder",
  'item.edit': "Edit",
  'item.delete': "Delete",
  'target.valid-squares': 'Which squares count as valid targets',
  'target.max-elevation-difference': 'Elevation difference beyond which a square is invalid',
  'target.unoccupied-only': 'Refuse a square another unit is standing on',
  'effect-param.numeric': 'If checked, this parameter expects numeric values',
  'effect-param.delete': 'Delete Parameter',
  'item.emit-an-aura-with-the-aura-modifiers-below': "Emit an aura with the Aura modifiers below",
  'item.drag-to-reorder-top-applied-first': "Drag to reorder (top applies first)",
  'item.aura-modifier-applies-to-actors-in-range-by-target-type': "Aura modifier",
  'animation.duration': 'Time after dispatch when damage applies',
  'animation.skip-cinematic': 'Skip the cinematic bars and camera pan when this item is used.',
  'animation.add-effect-step': 'Add effect step',
  'animation.add-sound-step': 'Add sound step',
  'animation.add-wait-step': 'Add wait step',
  'animation.copy-tab': "Copy this tab's steps and duration to the clipboard",
  'animation.paste-tab': 'Paste copied steps into this tab',
  'animation.preview-tab': "Preview this tab's animation",
  'crafting.forgeable': 'Forgeable at the Workshop',
  'crafting.forge-multiplier': 'Durability restored = skill roll × this, rounded',
  'crafting.forging-xp': 'Durability this copy has had restored by forging',
  'crafting.tier-enabled': 'Enable this tier',
  'crafting.xp-requirement': 'Forging XP the copy must have tallied to hold this tier',
  'crafting.tier-override': 'Blank inherits from the tier below, else the forging base',
  'crafting.damage-type-gain': 'Damage types the weapon gains at this tier',
  'crafting.copy-tier': index => `Copy every setting from (+${index}) into this tier`,
  'crafting.weight-reduction': 'Weight reduced by this amount',
  'crafting.durability-gain': 'Maximum durability gained at this tier',
  'modifier.name': 'Display name for this modifier',
  'modifier.target': 'Stat key, or an expression that resolves to one',
  'modifier.quantity': 'Number or SafeEval expression added to the stat',
  'modifier.target-type': 'Who this aura modifier applies to',
  'modifier.requires-equipped': 'Only apply this modifier while the item is wielded/worn/equipped',
  'modifier.requires-activation': 'Only applies while this item is active',
  'modifier.stackable': 'Off: a target is affected once regardless of carriers',
  'modifier.copy-condition': "Copy this modifier's condition tree to the clipboard",
  'modifier.paste-condition': 'Paste a copied condition',
  'uses-formula.base': 'Editing this updates the inline field as well',
  'uses-formula.line-of-sight': "How this ability's range/radius treats line of sight",

  // Type toggles on the item and Object sheets
  'type.arcane': 'Arcane',
  'type.armor': 'Armor',
  'type.beast': 'Beast',
  'type.blade': 'Blade',
  'type.bow': 'Bow',
  'type.brawling': 'Brawling',
  'type.cavalry': 'Cavalry',
  'type.covert': 'Covert',
  'type.crushing': 'Crushing',
  'type.decay': 'Decay',
  'type.divine': 'Divine',
  'type.dragon': 'Dragon',
  'type.elemental': 'Elemental',
  'type.fire': 'Fire',
  'type.flying': 'Flying',
  'type.heavy': 'Heavy',
  'type.holy': 'Holy',
  'type.ice': 'Ice',
  'type.infantry': 'Infantry',
  'type.lightning': 'Lightning',
  'type.magic': 'Magic',
  'type.missile': 'Missile',
  'type.monster': 'Monster',
  'type.occult': 'Occult',
  'type.piercing': 'Piercing',
  'type.polearm': 'Polearm',
  'type.shadow': 'Shadow',
  'type.slashing': 'Slashing',
  'type.undead': 'Undead',
  'type.wind': 'Wind',

  // Encounter tracker, plus the map settings in Scene Config and the Terrain Builder
  [ENCOUNTER_TOOLTIP_IDS.AUTO_ADVANCE]: 'Advance the phase when every unit has acted',
  [ENCOUNTER_TOOLTIP_IDS.COMBAT_MUSIC]: "Play this map's phase tracks on each phase change",
  [ENCOUNTER_TOOLTIP_IDS.PLAYER_PHASE_TRACK]:
    'Track or playlist played while this map is in combat during the Player Phase',
  [ENCOUNTER_TOOLTIP_IDS.ENEMY_PHASE_TRACK]:
    'Track or playlist played while this map is in combat during the Enemy Phase',
  [SCENE_TOOLTIP_IDS.MAP_VISIBLE]: 'Keep Fog of War, but reveal the whole map as explored',
  [SCENE_TOOLTIP_IDS.MOVEMENT_PERMISSION]: 'Restrict special movement on this map',
  [SCENE_TOOLTIP_IDS.MOVE_SCALING]: 'Scale every unit\'s movement on this map',
  [SCENE_TOOLTIP_IDS.TOKEN_OUTLINE_RESET]: 'Reset to global default',
  [ENCOUNTER_TOOLTIP_IDS.PHASE_PROGRESS]: ({ acted, total }) =>
    `${acted ?? 0} of ${total ?? 0} active units have acted`,
  [ENCOUNTER_TOOLTIP_IDS.SORT_FIELD]: 'Toggle sort field',
  [ENCOUNTER_TOOLTIP_IDS.SORT_DIRECTION]: ({ sortDir }) =>
    (sortDir === 'desc' ? 'Descending' : 'Ascending'),
  [ENCOUNTER_TOOLTIP_IDS.PREVIOUS_PAGE]: 'Previous page',
  [ENCOUNTER_TOOLTIP_IDS.NEXT_PAGE]: 'Next page',
  [ENCOUNTER_TOOLTIP_IDS.OBJECTIVE_TARGET]: 'Victory condition target',
  [ENCOUNTER_TOOLTIP_IDS.PROTECTED_UNIT]: 'Protected: losing this unit loses the map',
  [ENCOUNTER_TOOLTIP_IDS.ARRIVED_UNIT]: 'Arrived at an Arrival Point',
  [ENCOUNTER_TOOLTIP_IDS.LORD_UNIT]: 'Lord',
  [ENCOUNTER_TOOLTIP_IDS.EMITTING_AURA]: 'Emitting an aura',
  [ENCOUNTER_TOOLTIP_IDS.SET_OBJECTIVES]: 'Define how this encounter is won',
  [ENCOUNTER_TOOLTIP_IDS.EDIT_OBJECTIVES]: 'Change the win and loss conditions',
  [ENCOUNTER_TOOLTIP_IDS.BEGIN_ENCOUNTER]: 'Begin this encounter',
  [ENCOUNTER_TOOLTIP_IDS.CANCEL_ENCOUNTER]: 'Discard this encounter and return to setup',
  [ENCOUNTER_TOOLTIP_IDS.END_SUCCESS]: 'Declare the map cleared (players win)',
  [ENCOUNTER_TOOLTIP_IDS.END_FAILURE]: 'Declare the map lost (players defeated)',
  [ENCOUNTER_TOOLTIP_IDS.PAUSE_ENCOUNTER]: 'Stop this encounter, keeping its round for a later resume',
  [ENCOUNTER_TOOLTIP_IDS.RESUME_ENCOUNTER]: 'Open this map again on the round it was paused',
  [ENCOUNTER_TOOLTIP_IDS.DISCARD_PAUSE]: 'Discard the paused encounter',
  [ENCOUNTER_TOOLTIP_IDS.END_MENU_BACK]: 'Back',
  [ENCOUNTER_TOOLTIP_IDS.RESET_DOWNTIME]: 'Restores every unit\'s Downtime Action and Energy, '
    + 'clears downtime buffs, haggles and buybacks, and unlocks requisitioned factions',

  // Combat Preview
  'combat-preview.two-handed-shield': 'Cannot equip two-handed while using a Shield',
  'combat-preview.random-damage-type': 'Damage type will be randomized between these options',

  // Item authoring editors: dialog field labels, step cards and editor buttons
  'editor.card.drag': 'Drag to reorder, or to move between branches',
  'editor.card.collapse': 'Show or hide this step',
  'editor.card.duplicate': 'Duplicate this step below it',
  'editor.card.delete': 'Delete this step',
  'editor.card.kind': ({ kind }) => `Step kind: ${kind}`,
  'editor.save-disabled': ({ error }) => (error ? `Fix this before saving. ${error}` : 'Nothing to save yet'),
  'editor.effect.trigger': 'When this effect runs',
  'editor.effect.name': 'Optional label shown on the item sheet and in the window title',
  'editor.effect.hold-pose': "Keep the caster's cast pose until every step here has finished",
  'editor.effect.delay': 'Wait this long after the trigger before the first step runs',
  'editor.effect.item-names': 'Only when one of these items is used (one exact name per line)',
  'editor.effect.add-step': 'Add a step to the end of this list',
  'editor.effect.template': 'Start this effect from a stock set of steps',
  'editor.step.who': 'Which unit this applies to',
  'editor.step.area-center': 'Where the area is centred',
  'editor.step.area-radius': 'Radius of the area in squares',
  'editor.step.area-faction': 'Which units inside the area are affected',
  'editor.step.area-include-center': 'Whether the centre square itself counts',
  'editor.damage.amount': 'Dice or an expression, for example 1d6 or selfMgt',
  'editor.damage.type': 'Damage type',
  'editor.damage.stance': 'Break dealt alongside the HP damage',
  'editor.damage.mitigation': 'Reduce by Def or Res, armour and protections',
  'editor.damage.critical': 'Whether the damage is critical',
  'editor.heal.amount': 'Dice or an expression, for example 1d6 or selfCha',
  'editor.heal.stance': 'Optional stance points healed with the HP',
  'editor.shield.amount': 'Shield points to add, as a number or an expression',
  'editor.shield.cap': 'The shield never exceeds this (blank means no cap)',
  'editor.status.preset': 'The status to apply',
  'editor.status.duration': 'How many phases the status lasts',
  'editor.status.phases': 'How many phases the status lasts. 0 means it lasts until a trigger removes it',
  'editor.status.reapplication': 'Applying it again renews the duration, or adds to what is left',
  'editor.status.linked-tag':
    'An Animation or Change faction step with this tag as its link stays on the unit only while this status lasts',
  'editor.status.name': 'The name the status shows on the token and in effect lists',
  'editor.status.icon': 'The icon shown on the token while the status lasts',
  'editor.status.browse-icon': 'Browse for an icon',
  'editor.status.polarity': 'All harmful and all beneficial on a Remove status step take off statuses of that kind. '
    + 'A neutral status stays unless a step names it or ticks all neutral',
  'editor.status.hidden-on-token': "Keep this status off the token's icon list and the HUD",
  'editor.status.description': 'A short rule text shown with the status',
  'editor.status.ends-when': 'Each checked trigger removes one phase of duration, or one stack when set beneath it. '
    + 'The status ends at zero phases or at its last stack',
  'editor.status.ends.phase-begin': "Fires at the start of the unit's own faction phase",
  'editor.status.ends.phase-end': "Fires at the end of the unit's own faction phase",
  'editor.status.ends.any-phase-end': 'Fires at the end of every phase, player and enemy alike',
  'editor.status.ends.exchange-end': 'Fires at the end of each attack exchange the unit takes part in',
  'editor.status.ends.stance-break': "Fires when the unit's stance breaks",
  'editor.status.ends.attacked': 'Fires after every blow against the unit, hit or miss',
  'editor.status.ends.hostile-action': 'Fires when the unit takes a hostile action',
  'editor.status.ends.hostile-targeted': 'Fires when a hostile unit targets the unit',
  'editor.status.sheds': 'What this trigger removes when it fires: one phase of duration, or one stack',
  'editor.status.stackable': 'Applying it again also adds a stack. Each stack multiplies the added values',
  'editor.status.stack-count': 'Stacks added by each application',
  'editor.status.stack-limit': 'Most stacks the unit can carry (blank means no limit)',
  'editor.status.stack-hit': 'Being hit sheds one stack',
  'editor.status.change-target': 'The stat or flag this status changes',
  'editor.status.change-type': 'Add to the value, or replace it outright',
  'editor.status.change-value': 'The amount added, or the value set',
  'editor.status.change-priority': 'Order the changes apply in, lowest first. Adds use 20, overrides 99',
  'editor.status.change-delete': 'Delete this change',
  'editor.status.add-change': 'Add a change',
  'editor.status.advanced-json':
    'Other ActiveEffect data for this status, as JSON. The fields above are not repeated here',
  'editor.remove.who': 'Which units lose statuses: self, the target, or every unit with a token on this scene',
  'editor.remove.which': 'One status by its name, or every status of the kinds ticked below',
  'editor.remove.amount': 'How much of each status comes off: all of it, a number of stacks, or a number of phases',
  'editor.remove.count': 'How many stacks or phases. A status that does not stack counts as one stack. '
    + 'A status that lasts until a trigger removes it has no phases to take, so it stays',
  'editor.remove.applied-by': 'Only remove statuses this unit put on. Self is the unit using the item and target is '
    + 'the unit it is used on. Anyone removes them whoever put them on',
  'editor.remove.name': 'The status to remove, as its name reads on the token. '
    + 'Upper and lower case, spaces and punctuation do not matter',
  'editor.remove.kind-harmful': 'Remove every harmful status, such as Poisoned or Marked',
  'editor.remove.kind-beneficial': 'Remove every beneficial status, such as Blessed or Charged',
  'editor.remove.kind-neutral': 'Remove every neutral status, such as Berserk or Winded. '
    + 'All harmful and all beneficial leave these alone',
  'editor.remove.except': 'A unit on the map that keeps its statuses',
  'editor.faction.faction': 'The faction the unit joins',
  'editor.faction.grant-ownership': 'The caster\'s player also owns the unit until the linked status ends',
  'editor.faction.linked-tag':
    'The id tag of an earlier Apply status step on this unit, which changes back when that status ends',
  'editor.move.who': 'Which token is moved',
  'editor.move.how': 'How the token moves',
  'editor.move.pair': 'The other token the push, pull or swap is measured against',
  'editor.move.distance': 'How many squares to move',
  'editor.move.to': 'Where the teleport lands',
  'editor.move.dx': 'Squares to move right, or left if negative',
  'editor.move.dy': 'Squares to move down, or up if negative',
  'editor.move.ignore-walls': 'Move through walls and occupied squares',
  'editor.geometry.template': 'Start from a common placement rule',
  'editor.geometry.who': 'Whose footprint has to fit on the square',
  'editor.geometry.size': 'Width and height of the footprint, in squares',
  'editor.geometry.anchor': 'The token or square the distance is measured from',
  'editor.geometry.distance': 'Allowed distance from the anchor, inclusive',
  'editor.geometry.reach': 'How the unit reaches the square',
  'editor.geometry.budget': 'What limits the walk',
  'editor.geometry.budget-value': 'The most squares the walk may cost',
  'editor.geometry.diagonals': 'How a diagonal step is counted',
  'editor.geometry.elevation': 'How elevation is checked',
  'editor.geometry.los': 'Only count squares the anchor can see',
  'editor.geometry.min-count': 'The check passes when at least this many squares qualify',
  'editor.geometry.pick': 'Which qualifying square the move uses',
  'editor.animation.persistent': 'Keep playing after the effect resolves',
  'editor.animation.await': 'Later steps wait until this animation has finished',
  'editor.animation.edit': 'Open the animation editor',
  'editor.animation.tag': 'Links this animation to the Apply status step with the same tag',
  'editor.animation.tie-name': 'Status whose removal ends this animation',
  'editor.floating.text': 'The text shown over the unit',
  'editor.floating.color': 'Text colour as a hex value',
  'editor.floating.font-size': 'Text size in pixels',
  'editor.floating.offset-y': 'Vertical start offset in pixels, up if negative',
  'editor.floating.duration': 'How long the text stays, in milliseconds',
  'editor.spawn.actor': 'The actor to place, by UUID',
  'editor.spawn.location': 'Where the token is placed',
  'editor.spawn.name': 'Optional name for the placed token',
  'editor.spawn.friendly': 'The spawned unit joins the caster\'s side',
  'editor.spawn.owned': 'The caster\'s player also owns the spawned unit',
  'editor.spawn.sickness': 'The spawned unit cannot act until the next phase',
  'editor.spawn.duration': 'If # is not 0, summoned token expires after # phases.',
  'editor.spawn.replace': 'Removes the caster\'s earlier summons of this unit before placing the new one.',
  'editor.restore.standard': 'Give the unit its standard action back',
  'editor.restore.bonus': 'Give the unit its bonus action back',
  'editor.restore.movement': 'Give the unit its movement back',
  'editor.restore.full': 'Give the unit its whole turn back',
  'editor.voice.category': 'Which of the unit\'s voice lines plays',
  'editor.voice.skip-self': 'Stay silent when the speaker is the caster',
  'editor.wait.ms': 'How long to pause before the next step, in milliseconds',
  'editor.unequip.who': 'Whose wielded weapon is put away',
  'editor.terrain.overwrite': 'Replace what the square already has',
  'editor.terrain.replace-previous': 'Remove the last edit this item made before applying this one',
  'editor.terrain.duration': 'How many phases the edit lasts. 0 is permanent',
  'editor.terrain.preset': 'A saved tile',
  'editor.terrain.stat': 'Added to the stat of any unit standing on the square',
  'editor.terrain.effect': 'A hazard or healing the square applies each phase',
  'editor.terrain.variable': 'The size of the hazard or healing, 1 or more',
  'editor.terrain.stn': 'Stance restored along with the healing',
  'editor.terrain.can-kill': 'The hazard may reduce a player unit to zero HP',
  'editor.terrain.vfx': 'A Sequencer effect drawn on the square while the edit lasts',
  'editor.terrain.light': 'A light source placed on the square while the edit lasts',
  'editor.requirement.type': 'What kind of check this is',
  'editor.requirement.name': 'Optional label shown on the item sheet',
  'editor.condition.summary': 'The item can be used only while this holds',
  'editor.modifier.name': 'Label shown on the item sheet and in the character\'s modifier list',
  'editor.modifier.stat': 'The stat this changes, as a key or an expression',
  'editor.modifier.amount': 'Added to the stat, as a number or an expression',
  'editor.modifier.equipped': 'Only while the item is wielded, worn or equipped',
  'editor.modifier.active': 'Only while this item is active',
  'editor.modifier.applies-to': "Who inside the aura's range receives this modifier",
  'editor.modifier.stackable': 'Applies once per carrier in range',
  'editor.modifier.condition': 'The modifier applies only while this condition holds',
  'editor.target.type': 'Who the item may be aimed at',
  'editor.target.shape': 'The shape of the targeting grid',
  'editor.target.grid-colour': 'Colour of the highlighted squares while targeting',
  'editor.uses.type': 'How uses are counted',
  'editor.scaling.factor': 'What the value grows with',
  'editor.scaling.type': 'How the value scales',
  'editor.scaling.base': 'The value before scaling',
  'editor.scaling.preview': 'The computed value for the unit this item is on',
  'editor.scaling.threshold-at': 'When the scaling factor reaches this value',
  'editor.scaling.threshold-uses': 'The result at that threshold',
  'editor.scaling.add-threshold': 'Add another threshold',
  'editor.scaling.multiplier': 'The scaling factor is multiplied by this',
  'editor.scaling.add-to-base': 'Add the result to the base',
  'editor.scaling.formula': 'An expression using scaleFactor, for example (5 + scaleFactor) / 2',
  'editor.scaling.round-down': 'Round the result down',
  'editor.crafting.skill': 'Skill rolled to craft this',
  'editor.crafting.tier-skill': 'Skill rolled to forge this tier (blank inherits from the tier below)',
  'editor.crafting.difficulty': 'The roll a crafter must meet to make this',
  'editor.crafting.materials': 'Resources consumed per attempt',
  'editor.crafting.xp-needed': 'Forging XP a copy must have earned to reach this tier',
  'editor.crafting.forge-multiplier':
    'Durability restored per forge equals the skill roll times this (blank inherits from the tier below)',
  'editor.crafting.sync': ({ index }) => `Copy every setting from +${index} into this tier`,
  'editor.params.required-check': 'Whether the target must fail a roll for the effect to land',
  'editor.params.base-dc': "Difficulty before the caster's attribute is added",
  'editor.params.caster-adds': 'Caster attribute added to the DC',
  'editor.params.target-rolls': 'Attribute the target rolls against the DC',
  'editor.params.target-adds': 'Target attribute added to the skill check',
  'editor.params.skill': 'Skill the target rolls',
  'editor.params.friendlies': 'Friendly units pass the check without rolling',
  'editor.params.custom-name': 'Name of the parameter as effects refer to it',
  'editor.params.custom-options': 'Allowed values, comma separated, or a formula',
  'editor.params.add': 'Add a custom parameter',
  'editor.anim.file': 'Sequencer database path or file',
  'editor.anim.delay': 'Wait this long before the step starts, in milliseconds',
  'editor.anim.duration': 'How long the step plays, in milliseconds (blank plays the file once)',
  'editor.anim.wait': 'Later steps wait until this one has finished',
  'editor.anim.per-target': 'Play once per target',
  'editor.anim.at-location': 'Where the effect is placed',
  'editor.anim.attach-to': 'The token the effect follows while it plays',
  'editor.anim.stretch-to': 'The token or square the effect stretches toward',
  'editor.anim.rotate-towards': 'The token or square the effect faces',
  'editor.anim.rotate': 'Extra rotation in degrees',
  'editor.anim.layer': 'Which canvas layer draws the effect',
  'editor.anim.scale': 'Size multiplier',
  'editor.anim.scale-to-object': 'Size the effect to the token it plays on',
  'editor.anim.playback-rate': 'Speed multiplier for the file',
  'editor.anim.opacity': 'Opacity from 0 (invisible) to 1 (solid)',
  'editor.anim.hue': 'Hue shift in degrees',
  'editor.anim.fade-in': 'Fade in over this many milliseconds',
  'editor.anim.fade-out': 'Fade out over this many milliseconds',
  'editor.anim.offset': 'Offset from the anchor',
  'editor.anim.repeats': 'Play this many times, with a random delay between the two values',
  'editor.anim.start-time': 'Skip this far into the file, in milliseconds',
  'editor.anim.end-time': 'Cut this much off the end of the file, in milliseconds',
  'editor.anim.mirrors': 'Flip the effect on an axis, or flip it at random each time',
  'editor.anim.volume': 'Volume from 0 to 1',
  'editor.anim.channel': 'The audio channel the sound plays on',
  'editor.anim.fade-in-audio': 'Fade the sound in over this many milliseconds',
  'editor.anim.fade-out-audio': 'Fade the sound out over this many milliseconds',
  'editor.anim.advanced': 'Extra Sequencer options as JSON, merged into this step',
  'editor.anim.grid-units': 'Measure the offset in grid squares',
  'editor.condition.copy': 'Copy this condition to the clipboard',
  'editor.condition.paste': 'Paste a copied condition',
  'editor.scaling.threshold-delete': 'Delete this threshold',
  'editor.weapon.randomize-damage-type': 'Each strike deals one of the enabled damage types, picked at random',
  'editor.voice.speaker': "Which unit's voice line plays",
  'editor.terrain.vfx-scale': 'Size multiplier for the effect (1 fills the square)',
  'editor.terrain.vfx-opacity': 'Opacity of the effect from 0 (invisible) to 1 (solid)',
  'editor.terrain.vfx-rotation': 'Rotation of the effect in degrees',
  'editor.terrain.vfx-mirror-x': 'Flip the effect left to right',
  'editor.terrain.vfx-mirror-y': 'Flip the effect top to bottom',
  'editor.terrain.light-dim': 'Radius of the dim light in squares',
  'editor.terrain.light-bright': 'Radius of the bright light in squares',
  'editor.terrain.light-colour': 'Colour of the light',
  'editor.terrain.light-intensity': 'How strongly the colour tints the light, from 0 to 1',
  'editor.terrain.light-animation': 'The core light animation the light plays',
  'editor.terrain.light-speed': 'Speed of the light animation from 1 to 10',
  'editor.terrain.light-anim-intensity': 'Strength of the light animation from 1 to 10',
  'editor.terrain.light-walls': 'Walls stop the light',
  'editor.terrain.light-vision': 'Units can see by this light',
  'editor.terrain.light-coloration': 'The shader technique that blends the light with the scene',
  'editor.terrain.light-luminosity': 'Brightness of the light from -1 (darkness) to 1',
  'editor.terrain.light-attenuation': 'How quickly the light fades toward its edge, from 0 to 1',
  'editor.terrain.light-saturation': 'Colour saturation of the lit area from -1 to 1',
  'editor.terrain.light-contrast': 'Contrast of the lit area from -1 to 1',
  'editor.terrain.light-shadows': 'Depth of the shadows the light casts, from 0 to 1'
});

/* -------------------------------------------- */
/*  Tooltip lookup                              */
/* -------------------------------------------- */
/**
 * The tooltip text for a catalogue id, or '' for an unknown id; a function entry is called with `data`. The text
 * usually goes into `data-tooltip`, which Foundry renders as cleaned HTML. The `{{tooltip}}` Handlebars helper
 * passes its second argument through as `data` unchanged, so an entry may take a bare value.
 */
export function getTooltip(id, data = {}) {
  const definition = TOOLTIPS[id];
  return typeof definition === 'function' ? definition(data) : definition ?? '';
}
